abstract: WEB application framework release version.
author: Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>
build_requires: 
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Egg-Release
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI: 0
  Class::Accessor: 0
  Class::C3: 0
  Class::Data::Inheritable: 0
  DBI: 0
  Data::Dump: 0
  Devel::StackTrace: 0
  File::Copy: 0
  File::Path: 0
  File::Spec: 0
  File::Temp: 0
  File::Which: 0
  FileHandle: 0
  Getopt::Easy: 0
  HTML::Entities: 0
  HTML::FillInForm: 0
  HTML::Mason: 0
  HTML::Prototype: 0
  HTML::Template: 0
  HTTP::Date: 0
  HTTP::Headers: 0
  IO::Scalar: 0
  Jcode: 0
  ModPerl::VersionUtil: 0
  Module::Install: 0
  Tie::RefHash: 0
  Time::HiRes: 0
  UNIVERSAL::require: 0
  URI: 0
  YAML: 0
version: 1.16
