abstract: Version of Egg WEB Application Framework.
author: Masatoshi Mizuno E<lt>lusheE<64>cpan.orgE<gt>
build_requires: 
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Egg-Release
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI: 3.28
  Class::Accessor: 0.3
  Class::C3: 0.14
  Devel::StackTrace: 1.14
  Digest::MD5: 2.36
  File::Spec: 3.24
  File::Temp: 0.18
  File::Which: 0.05
  FileHandle: 2
  FormValidator::Simple: 0.22
  Getopt::Easy: 0.01
  HTML::FillInForm: 1.06
  HTML::Mason: 1.35
  HTML::Parser: 3.56
  HTML::Prototype: 1.48
  HTML::Template: 2.9
  Jcode: 2.06
  MIME::Base64: 3.07
  ModPerl::VersionUtil: 0.03
  Tie::RefHash: 1.35
  Time::HiRes: 0
  UNIVERSAL::require: 0.11
  URI: 1.35
  WWW::Mechanize::CGI: 0.03
  YAML: 0.62
version: 2.03
