abstract: WEB application framework release.
author: Masatoshi Mizuno, <mizunoE<64>bomcity.com>
build_requires: 
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Egg-Release
no_index: 
  directory: 
    - inc
    - t
requires: 
  CGI: 0
  CGI::Cookie: 0
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  DBI: 0
  Data::Dump: 0
  Error: 0
  File::Path: 0
  File::Temp: 0
  File::Which: 0
  FileHandle: 0
  HTML::Entities: 0
  HTML::Prototype: 0
  HTML::Template: 0
  HTTP::Date: 0
  HTTP::Headers: 0
  IO::Scalar: 0
  Jcode: 0
  NEXT: 0
  Test::More: 0
  Time::HiRes: 0
  UNIVERSAL::require: 0
  URI: 0
  YAML: 0
version: 0.12
